SELECT
    YEAR(e1.DIFFERENTIATION_DATE) AS YEAR,
    (
        SELECT MAX(e2.SIZE_OF_COLONY)
        FROM ECOLI_DATA e2
        WHERE YEAR(e2.DIFFERENTIATION_DATE)
              = YEAR(e1.DIFFERENTIATION_DATE)
    ) - e1.SIZE_OF_COLONY AS YEAR_DEV,
    e1.ID
FROM ECOLI_DATA e1
ORDER BY YEAR, YEAR_DEV;
