SELECT YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT USER.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT USER.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)='2021'),1) AS PURCHASED_RATIO
FROM USER_INFO AS USER
JOIN ONLINE_SALE AS SALE
ON USER.USER_ID=SALE.USER_ID
WHERE YEAR(JOINED)='2021'
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH
