-- 1) JOIN + DISTINCT
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS DEV
JOIN SKILLCODES SKILL
ON DEV.SKILL_CODE & SKILL.CODE
WHERE SKILL.CATEGORY = 'Front End'
ORDER BY ID;

-- 2) 서브쿼리 + SUM
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End') > 0
ORDER BY ID ASC;
